version: "3.1"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    env_file:
      - ".env"
    environment:
      KAFKA_LISTENERS: $KAFKA_LISTENERS
      KAFKA_ADVERTISED_LISTENERS: $KAFKA_ADVERTISED_LISTENERS
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: $KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      KAFKA_INTER_BROKER_LISTENER_NAME: $KAFKA_INTER_BROKER_LISTENER_NAME
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: $KAFKA_ZOOKEEPER_SESSION_TIMEOUT
      KAFKA_RESTART_ATTEMPTS: $KAFKA_RESTART_ATTEMPTS
      KAFKA_RESTART_DELAY: $KAFKA_RESTART_DELAY
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: $ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL